import type { Product, Category, Color } from "./types";

function product(id: string, slug: string, name: string, category: Category, price: number, originalPrice: number, image: string, colors: Color[], sizes: string[], description: string, fabric: string, badge?: string): Product {
  return { id, slug, name, category, price, originalPrice, image: `/images/${image}.jpg`, images: [`/images/${image}.jpg`, `/images/${image}-detail.jpg`], colors, sizes, description, fabric, care: "Gentle machine wash cold with similar colours. Do not bleach. Dry in shade. Warm iron on reverse.", badge, variants: sizes.flatMap((size, i) => colors.map(color => ({ size, color: color.name, stock: i === sizes.length - 1 ? 4 : 12 }))) };
}
export const CATALOG: Product[] = [
  product("linen-shirt", "relaxed-linen-shirt", "Relaxed Linen Shirt", "Men", 699, 999, "category-men", [{name:"Sand",hex:"#c3b298"},{name:"Olive",hex:"#62684b"},{name:"Charcoal",hex:"#353537"}], ["S","M","L","XL","XXL"], "Your off-duty uniform, elevated. An airy linen-blend shirt with a relaxed silhouette, natural texture and endless styling possibilities. Made for sunlit mornings and unplanned evenings.", "55% linen, 45% cotton. Breathable, lightweight weave.", "BESTSELLER"),
  product("floral-kurta", "floral-everyday-kurta", "Floral Everyday Kurta", "Women", 799, 1199, "category-women", [{name:"Terracotta",hex:"#a84e37"},{name:"Sage",hex:"#8c9880"}], ["XS","S","M","L","XL"], "A little tradition. A lot of you. Delicate floral motifs meet a modern easy fit in this everyday cotton kurta. Pair with your favourite palazzos or keep it casual with denim. Bottoms not included.", "100% soft cotton with an all-over floral print.", "JUST DROPPED"),
  product("textured-tee", "essential-textured-tee", "Essential Textured Tee", "Men", 399, 599, "product-tee", [{name:"Forest",hex:"#515b3a"},{name:"Black",hex:"#242424"},{name:"Chalk",hex:"#dfdcd0"}], ["S","M","L","XL"], "The tee you will reach for on repeat. Rich cotton texture, a clean crew neck and a just-right relaxed fit make everyday dressing feel a little more considered.", "100% textured cotton jersey, 180 GSM.", "EVERYDAY FAVOURITE"),
  product("kids-set", "weekend-explorer-set", "Weekend Explorer Set", "Kids", 599, 899, "category-kids", [{name:"Navy",hex:"#46586c"},{name:"Mustard",hex:"#c5a151"}], ["3–4 Y","5–6 Y","7–8 Y","9–10 Y"], "Big adventures start with little outfits. A soft tee and easy pull-on shorts, designed for busy days, playground detours and everything in between. One two-piece set per order.", "100% cotton top and cotton-twill elasticated shorts.", "PLAY ALL DAY"),
  product("baby-knit", "soft-start-knit-set", "Soft Start Knit Set", "Infants", 499, 699, "category-infants", [{name:"Oatmeal",hex:"#cfbda2"},{name:"Cloud",hex:"#e9e6db"}], ["0–3 M","3–6 M","6–12 M","12–18 M"], "Little moments, the softest layers. This ribbed cotton top and matching trousers are gentle on delicate skin and made for all-day wriggles and cuddles.", "100% soft-touch cotton rib knit. Nickel-free fastening.", "SOFT LITTLE THINGS"),
  product("wide-denim", "the-wide-leg-denim", "The Wide-Leg Denim", "Women", 999, 1499, "product-denim", [{name:"Vintage Blue",hex:"#7591a9"},{name:"Midnight",hex:"#343f55"}], ["26","28","30","32","34"], "Good denim. Great days. A flattering high-rise waist and an easy wide leg bring a fresh perspective to your everyday rotation. Finished with classic five-pocket detailing.", "99% cotton, 1% elastane. Mid-weight washed denim.", "THE DENIM EDIT"),
  product("court-sneakers", "everyday-court-sneakers", "Everyday Court Sneakers", "Men", 1299, 1699, "product-sneakers", [{name:"Cream",hex:"#dfd8c7"}], ["6","7","8","9","10"], "A clean finish for every look. Retro court-inspired sneakers with soft lining, a cushioned footbed and understated tonal detailing. Your everyday, upgraded.", "Synthetic leather upper, textile lining, durable rubber outsole."),
  product("baby-top", "little-cloud-cotton-top", "Little Cloud Cotton Top", "Infants", 299, 449, "category-infants", [{name:"Oatmeal",hex:"#cfbda2"}], ["0–3 M","3–6 M","6–12 M","12–18 M"], "An extra-soft ribbed top for the littlest wardrobe. Easy dressing, gentle seams and a comfortable stretch. Top only; the coordinating trousers are available in the Soft Start Knit Set.", "100% breathable ribbed cotton.", "UNDER ₹499"),
];
export const CATEGORIES = [
  {name:"Men" as Category, caption:"The everyday, elevated.", image:"/images/category-men.jpg", number:"01"},
  {name:"Women" as Category, caption:"A little more you.", image:"/images/category-women.jpg", number:"02"},
  {name:"Kids" as Category, caption:"Big style. Little humans.", image:"/images/category-kids.jpg", number:"03"},
  {name:"Infants" as Category, caption:"Soft starts. Sweet style.", image:"/images/category-infants.jpg", number:"04"},
];
export const STORE_ADDRESS = "Rajender Path, Babunia More, Chhapra Road, Near Fatehpur Bypass Rd, Pal Nagar, Siwan, Bihar 841226";
export const MAP_QUERY = "V-Mart Rajender Path Babunia More Siwan Bihar 841226";
export const MAP_URL = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(MAP_QUERY)}`;
