"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, CreditCard, Landmark, LockKeyhole, Mail, MapPin, Phone, Printer, ShieldCheck, ShoppingBag, Smartphone, Store, Truck, User, Info, LoaderCircle } from "lucide-react";
import { useShop } from "./shop-provider";
import { Button } from "./ui/button";
import { DeliveryCheck } from "./delivery-check";
import { money, lineKey, type Customer, type CartLine } from "@/lib/types";
import { STORE_ADDRESS } from "@/lib/catalog";
type Receipt={orderId:string;total:number;name:string;delivery:string;items:(CartLine&{name:string;price:number})[]};
const emptyCustomer:Customer={name:"",email:"",phone:"",address:"",city:"Siwan",pin:"",delivery:"delivery"};
export function Checkout() {
  const {cart,products,ready,refresh,setCartOpen,notify}=useShop();const router=useRouter();const query=useSearchParams();const orderId=query.get("order");const reduced=useReducedMotion();
  const [step,setStep]=useState(0);const [customer,setCustomer]=useState<Customer>(emptyCustomer);const [payment,setPayment]=useState("upi");const [bank,setBank]=useState("State Bank of India");const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [receipt,setReceipt]=useState<Receipt|null>(null);const [receiptLoading,setReceiptLoading]=useState(!!orderId);const [decline,setDecline]=useState(false);
  useEffect(()=>{if(!orderId||!ready)return;let live=true;setReceiptLoading(true);fetch(`/api/orders/${encodeURIComponent(orderId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(live)setReceipt(data);}).catch(err=>{if(live){notify(err instanceof Error?err.message:"Unable to find that order.");router.replace("/checkout");}}).finally(()=>{if(live)setReceiptLoading(false);});return()=>{live=false;};},[orderId,ready,notify,router]);
  const receiptId=receipt?.orderId;
  useEffect(()=>{if(receiptId)window.scrollTo(0,0);},[receiptId]);
  const subtotal=cart.reduce((sum,line)=>sum+(products.find(p=>p.id===line.productId)?.price??0)*line.quantity,0);
  const savings=cart.reduce((sum,line)=>{const product=products.find(p=>p.id===line.productId);return sum+(product?product.originalPrice-product.price:0)*line.quantity;},0);
  const shipping=customer.delivery==="pickup"||subtotal>=999?0:49;const total=subtotal+shipping;
  function update<K extends keyof Customer>(key:K,value:Customer[K]){setCustomer(prev=>({...prev,[key]:value}));setError("");}
  function goToStep(next:number){setError("");setStep(next);document.getElementById("checkout-top")?.scrollIntoView({block:"start"});}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(step<2){if(customer.delivery==="delivery"&&(!/^[1-8]\d{5}$/.test(customer.pin)||customer.address.trim().length<8)){setError("Please add your complete address and a valid six-digit PIN code.");setStep(0);return;}goToStep(step+1);return;}if(!consent){setError("Please acknowledge that this is a prototype before continuing.");return;}if(decline){setError("Simulated payment declined. No money was charged. Switch off the failure test or choose another method to try again.");setDecline(false);return;}setBusy(true);try{const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,paymentMethod:payment})});const data=await response.json();if(!response.ok)throw new Error(data.error);setReceipt({...data,name:customer.name,delivery:customer.delivery});await refresh();router.replace(`/checkout?order=${data.orderId}`,{scroll:false});}catch(err){setError(err instanceof Error?err.message:"We couldn’t finish your demo order. Please try again.");}finally{setBusy(false);}}
  if(!ready||receiptLoading)return <main id="main-content" className="checkout-loading"><ShoppingBag size={34} strokeWidth={1.2}/><h1>Getting everything ready.</h1><p>A good look is worth a moment.</p></main>;
  if(receipt)return <main id="main-content" className="order-success container"><motion.div className="success-seal" initial={{scale:.5,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:250,damping:16}}><Check size={39}/></motion.div><div className="eyebrow">YOUR DEMO ORDER IS IN.</div><h1>LOOKING GOOD,<br/>SIWAN<span>.</span></h1><p>Thanks, {receipt.name.split(" ")[0]}. Your prototype order has been saved.<br/>No money was charged, and no items will be shipped.</p><div className="success-order-card"><div><span>ORDER REFERENCE</span><strong>{receipt.orderId}</strong></div><div><span>DEMO TOTAL</span><strong>{money(receipt.total)}</strong></div><div><span>YOUR CHOICE</span><strong>{receipt.delivery==="pickup"?"Store pickup":"Home delivery"}</strong></div></div><div className="receipt-items">{receipt.items.map(item=><div key={lineKey(item)}><span>{item.name} <small>{item.size} · {item.color} · Qty {item.quantity}</small></span><strong>{money(item.price*item.quantity)}</strong></div>)}</div><div className="success-actions"><Button asChild><Link href="/">Keep your style moving<ArrowRight size={17}/></Link></Button><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Print confirmation</Button></div><div className="prototype-note"><Info size={15}/>This confirmation belongs to a demo, not a real V-Mart order.</div></main>;
  if(!cart.length)return <main id="main-content" className="checkout-empty container"><div className="empty-state"><div className="empty-icon"><ShoppingBag size={38} strokeWidth={1.3}/></div><h1>FIRST, FIND YOUR FAVOURITES.</h1><p>Your bag is taking a little breather.<br/>Add a style you love, then we’ll meet you back here.</p><Button asChild><Link href="/#arrivals">Explore the new season<ArrowRight size={17}/></Link></Button></div></main>;
  return <main id="main-content" className="checkout-page"><div className="container"><div className="checkout-topline"><button className="text-link" onClick={()=>setCartOpen(true)}><ArrowLeft size={15}/>Back to your bag</button><span><LockKeyhole size={13}/>GUEST CHECKOUT <b>PROTOTYPE</b></span></div><div className="checkout-heading" id="checkout-top"><div className="eyebrow"><span className="small-line"/>A FEW GOOD CHOICES. A FEW SIMPLE STEPS.</div><h1>MAKE IT YOURS.</h1><p>No account needed. Just your next favourite look.</p></div><div className="checkout-layout"><div className="checkout-main"><nav className="checkout-steps" aria-label="Checkout progress">{["Your details","Delivery","Payment"].map((label,i)=><button type="button" key={label} className={`${step===i?"active":""} ${step>i?"completed":""}`} disabled={i>step||busy} aria-current={step===i?"step":undefined} onClick={()=>goToStep(i)}><span>{step>i?<Check size={14}/>:i+1}</span>{label}{i<2&&<span className="step-line"/>}</button>)}</nav><form className="checkout-form" onSubmit={submit}><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:reduced?0:14}} animate={{opacity:1,x:0}} exit={{opacity:0,x:reduced?0:-10}} transition={{duration:.23}}>
      {step===0&&<><div className="checkout-panel-heading"><User size={20}/><div><h2>THE PERSON BEHIND THE STYLE.</h2><p>Use fictional details to explore this prototype.</p></div></div><div className="form-grid"><label className="form-field full-span">Full name<input name="name" autoComplete="name" placeholder="Your full name" required minLength={2} maxLength={100} value={customer.name} onChange={e=>update("name",e.target.value)}/></label><label className="form-field">Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={180} value={customer.email} onChange={e=>update("email",e.target.value)}/></label><label className="form-field">Mobile number<div className="phone-input"><span>+91</span><input name="phone" aria-label="Mobile number" type="tel" autoComplete="tel-national" inputMode="numeric" placeholder="10-digit mobile number" pattern="[6-9][0-9]{9}" title="Enter a 10-digit Indian mobile number beginning with 6, 7, 8 or 9" required value={customer.phone} maxLength={10} onChange={e=>update("phone",e.target.value.replace(/\D/g,"").slice(0,10))}/></div></label></div><div className="fulfilment-choice" role="group" aria-label="Fulfilment preference"><button type="button" className={customer.delivery==="delivery"?"selected":""} onClick={()=>update("delivery","delivery")} aria-pressed={customer.delivery==="delivery"}><Truck size={17}/>Bring it to me</button><button type="button" className={customer.delivery==="pickup"?"selected":""} onClick={()=>update("delivery","pickup")} aria-pressed={customer.delivery==="pickup"}><Store size={17}/>I’ll collect in Siwan</button></div>{customer.delivery==="delivery"?<div className="form-grid shipping-fields"><label className="form-field full-span">Your delivery address<input name="address" autoComplete="street-address" placeholder="House / flat, street, locality" required minLength={8} maxLength={400} value={customer.address} onChange={e=>update("address",e.target.value)}/></label><label className="form-field">Town / city<input name="city" autoComplete="address-level2" placeholder="Town or city" required maxLength={100} value={customer.city} onChange={e=>update("city",e.target.value)}/></label><label className="form-field">PIN code<input name="pin" autoComplete="postal-code" inputMode="numeric" placeholder="6-digit PIN code" pattern="[1-8][0-9]{5}" title="A six-digit Indian PIN code, beginning with 1–8" required maxLength={6} value={customer.pin} onChange={e=>update("pin",e.target.value.replace(/\D/g,"").slice(0,6))}/></label></div>:<div className="pickup-preview"><MapPin size={19}/><p><strong>See you at Babunia More.</strong>{STORE_ADDRESS}<small>Demo preference only. No real store reservation is made.</small></p></div>}</>}
      {step===1&&<><div className="checkout-panel-heading"><Truck size={21}/><div><h2>YOUR STYLE. YOUR WAY.</h2><p>A doorstep delivery or a little trip to your store.</p></div></div><div className="contact-review"><span><strong>{customer.name}</strong><small>{customer.email} · +91 {customer.phone}</small></span><button type="button" onClick={()=>goToStep(0)}>Edit<ArrowRight size={13}/></button></div><div className="delivery-options"><label className={customer.delivery==="delivery"?"selected":""}><input type="radio" name="delivery-option" checked={customer.delivery==="delivery"} onChange={()=>{update("delivery","delivery");if(!customer.address||!customer.pin){goToStep(0);notify("Add your delivery address, then continue.");}}}/><Truck size={21}/><span><strong>Standard delivery</strong><small>{customer.pin.startsWith("841")?"Estimated 2–4 working days":"Estimated 5–7 working days"} · Demo</small></span><b>{subtotal>=999?"FREE":money(49)}</b></label><label className={customer.delivery==="pickup"?"selected":""}><input type="radio" name="delivery-option" checked={customer.delivery==="pickup"} onChange={()=>update("delivery","pickup")}/><Store size={21}/><span><strong>Collect at V-Mart Siwan</strong><small>Babunia More · 10:00 AM – 10:00 PM</small></span><b>FREE</b></label></div>{customer.delivery==="delivery"?<><div className="address-review"><MapPin size={16}/><p><strong>Deliver to</strong>{customer.address}, {customer.city} – {customer.pin}</p></div><DeliveryCheck pin={customer.pin} onPinChange={value=>update("pin",value)}/></>:<div className="pickup-preview"><MapPin size={19}/><p><strong>Your neighbourhood style stop.</strong>{STORE_ADDRESS}<small>Prototype pickup only. Please call the real store before visiting for an item.</small></p></div>}<div className="checkout-info"><Info size={16}/><p>Delivery and pickup are simulated. This order will not be fulfilled by the real store.</p></div></>}
      {step===2&&<><div className="checkout-panel-heading"><ShieldCheck size={21}/><div><h2>THE FINAL LITTLE STEP.</h2><p>A payment experience to try. Not a payment to make.</p></div></div><div className="payment-prototype-banner"><ShieldCheck size={19}/><span><strong>DEMO MODE — NO MONEY WILL BE CHARGED</strong><small>Razorpay-style prototype. Not connected to Razorpay.</small></span></div><div className="payment-tabs" role="group" aria-label="Prototype payment method">{[{id:"upi",label:"UPI",Icon:Smartphone},{id:"card",label:"Card",Icon:CreditCard},{id:"netbanking",label:"Netbanking",Icon:Landmark}].map(({id,label,Icon})=><button key={id} type="button" aria-pressed={payment===id} className={payment===id?"selected":""} onClick={()=>{setPayment(id);setError("");}}><Icon size={19}/>{label}{payment===id&&<Check size={13}/>}</button>)}</div><div className="payment-preview">{payment==="upi"?<><div className="upi-wordmark">UPI<span>▰</span></div><h3>One tap. A simulated payment.</h3><p>Use our preconfigured test UPI flow.<br/>No real UPI ID, PIN, or banking app is needed.</p><div className="test-payment-pill"><CheckCircle2 size={15}/>V-Mart test account · Success mode</div></>:payment==="card"?<><div className="demo-bank-card"><div><span>V-MART / TEST CARD</span><CreditCard size={23}/></div><strong>4242&nbsp; 4242&nbsp; 4242&nbsp; 4242</strong><div><span>STYLE EXPLORER</span><span>12 / 30</span></div></div><p>This test card is already configured. Never enter real card details in a prototype.</p></>:<><Landmark size={30}/><h3>Choose a test bank.</h3><label className="form-field"><span className="sr-only">Demo bank</span><select aria-label="Demo bank" value={bank} onChange={e=>setBank(e.target.value)}><option>State Bank of India</option><option>HDFC Bank</option><option>ICICI Bank</option><option>Punjab National Bank</option></select></label><p>No bank login opens. This choice only simulates the experience.</p></>}</div><label className="prototype-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I understand this is a prototype. No payment will be collected and no real order will be placed.</span></label><label className="decline-control"><input type="checkbox" checked={decline} onChange={e=>setDecline(e.target.checked)}/><span>Test a declined payment instead</span></label></>}
    </motion.div></AnimatePresence>{error&&<div className="checkout-error" role="alert"><Info size={17}/>{error}</div>}<div className="checkout-form-actions">{step>0&&<button type="button" className="text-link" disabled={busy} onClick={()=>goToStep(step-1)}><ArrowLeft size={15}/>Go back</button>}<Button type="submit" disabled={busy||!ready}>{busy?<><motion.span animate={reduced?{}:{rotate:360}} transition={{repeat:Infinity,duration:1,ease:"linear"}}><LoaderCircle size={17}/></motion.span>Saving your demo order…</>:step===0?<>Continue to delivery<ArrowRight size={17}/></>:step===1?<>Continue to payment<ArrowRight size={17}/></>:<>Place demo order · {money(total)}<LockKeyhole size={16}/></>}</Button></div><p className="checkout-security-note"><LockKeyhole size={12}/>Your session is private. No real payment details are collected.</p></form></div>
      <aside className="checkout-summary"><div className="summary-heading"><h2>GOOD CHOICES.</h2><button onClick={()=>setCartOpen(true)}>Edit bag<ArrowRight size={13}/></button></div><div className="summary-items">{cart.map(line=>{const product=products.find(p=>p.id===line.productId);if(!product)return null;return <div key={lineKey(line)}><div className="summary-item-image"><img src={product.image} alt={product.name} width={65} height={85}/><span>{line.quantity}</span></div><span><strong>{product.name}</strong><small>{line.color} / {line.size}</small><b>{money(product.price*line.quantity)}</b></span></div>;})}</div><div className="summary-totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>{customer.delivery==="pickup"?"Store pickup":"Delivery"}</span><strong className={shipping===0?"free-delivery":""}>{shipping===0?"Complimentary":money(shipping)}</strong></div><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><p>Inclusive of all taxes</p></div><div className="savings-note"><CheckCircle2 size={15}/>A little win: you’re saving {money(savings)}.</div><div className="summary-prototype-note"><ShieldCheck size={25}/><p><strong>A real experience. A demo order.</strong>Explore freely. Nothing is charged or shipped.</p></div></aside>
    </div></div></main>;
}
