"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, Heart, ShoppingBag, Minus, Plus, Trash2, Search, Truck, ShieldCheck, Check, SlidersHorizontal } from "lucide-react";
import { useShop } from "./shop-provider";
import { Dialog } from "./ui/dialog";
import { Button } from "./ui/button";
import { lineKey, money, type Product } from "@/lib/types";

function QuickAdd({product,initialColor}: {product:Product;initialColor:string}) {
  const {addToCart,pending,ready,setQuickProduct} = useShop();
  const [size,setSize] = useState(""); const [color,setColor] = useState(initialColor);
  const variant = product.variants.find(v=>v.size===size&&v.color===color);
  return <div className="quick-product"><img src={product.image} alt={product.name} width={400} height={500}/><div><span className="eyebrow muted">{product.category} / NEW SEASON</span><h3>{product.name}</h3><div className="product-price"><strong>{money(product.price)}</strong><del>{money(product.originalPrice)}</del></div><p className="field-label">Colour: <strong>{color}</strong></p><div className="large-swatches">{product.colors.map(c=><button className={color===c.name?"selected":""} key={c.name} aria-label={c.name} aria-pressed={color===c.name} onClick={()=>setColor(c.name)} style={{background:c.hex}}>{color===c.name&&<Check size={15}/>}</button>)}</div><p className="field-label">Choose your size</p><div className="size-grid">{product.sizes.map(s=>{const available=product.variants.some(v=>v.size===s&&v.color===color&&v.stock>0);return <button key={s} className={size===s?"selected":""} disabled={!available} aria-pressed={size===s} onClick={()=>setSize(s)}>{s}</button>;})}</div><Button className="full-width" disabled={!variant?.stock||pending||!ready} onClick={()=>addToCart(product,size,color)}>{pending?"Adding…":!size?"Select a size":"Add to bag"}<ShoppingBag size={18}/></Button><Link className="text-link" href={`/product/${product.slug}`} onClick={()=>setQuickProduct(null)}>View all product details <ArrowRight size={14}/></Link></div></div>;
}
export function CommerceOverlays() {
  const shop = useShop(); const {cart,products,wishlist,cartOpen,setCartOpen,wishlistOpen,setWishlistOpen,searchOpen,setSearchOpen,quickProduct,setQuickProduct,updateQuantity,removeItem,toggleWishlist,pending,ready} = shop;
  const [query,setQuery] = useState("");
  const subtotal = cart.reduce((sum,line)=>sum+(products.find(p=>p.id===line.productId)?.price??0)*line.quantity,0);
  const count=cart.reduce((sum,line)=>sum+line.quantity,0);
  const results=useMemo(()=>products.filter(p=>`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query.toLowerCase().trim())),[query,products]);
  return <>
    <Dialog open={cartOpen} onOpenChange={setCartOpen} title={`Your bag (${count})`} description="Good choices look great on you." sheet>
      {cart.length ? <><div className="shipping-progress"><p><Truck size={17}/>{subtotal>=999?"Your bag qualifies for free delivery.":<>You’re <strong>{money(999-subtotal)}</strong> away from free delivery.</>}</p><div><motion.span animate={{width:`${Math.min(subtotal/999*100,100)}%`}}/></div><small>Prototype delivery offer</small></div><div className="cart-items"><AnimatePresence initial={false}>{cart.map(line=>{const product=products.find(p=>p.id===line.productId);if(!product)return null;const stock=product.variants.find(v=>v.size===line.size&&v.color===line.color)?.stock??0;return <motion.article layout key={lineKey(line)} className="cart-line" exit={{opacity:0,x:30}}><Link href={`/product/${product.slug}`} onClick={()=>setCartOpen(false)}><img src={product.image} alt={product.name} width={96} height={120}/></Link><div><span className="tiny-label">{product.category}</span><Link href={`/product/${product.slug}`} onClick={()=>setCartOpen(false)}>{product.name}</Link><p>{line.color} <span>·</span> {line.size}</p><div className="cart-line-bottom"><div className="quantity-control"><button aria-label={`Decrease ${product.name} quantity`} disabled={line.quantity<=1||pending} onClick={()=>updateQuantity(line,line.quantity-1)}><Minus size={13}/></button><span>{line.quantity}</span><button aria-label={`Increase ${product.name} quantity`} disabled={line.quantity>=Math.min(stock,10)||pending} onClick={()=>updateQuantity(line,line.quantity+1)}><Plus size={13}/></button></div><strong>{money(product.price*line.quantity)}</strong></div></div><button className="cart-remove" aria-label={`Remove ${product.name}`} disabled={pending} onClick={()=>removeItem(line)}><Trash2 size={16}/></button></motion.article>;})}</AnimatePresence></div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p>Inclusive of taxes. Delivery calculated at checkout.</p><Button asChild className="full-width"><Link href="/checkout" onClick={()=>setCartOpen(false)}>Continue to checkout<ArrowRight size={18}/></Link></Button><div className="secure-note"><ShieldCheck size={15}/> Secure experience · Prototype payments only</div><button className="continue-shopping" onClick={()=>setCartOpen(false)}>Keep exploring</button></div></> : <div className="empty-state"><div className="empty-icon"><ShoppingBag size={35} strokeWidth={1.25}/></div><h3>{ready?"Your next look is waiting.":"Getting your bag ready…"}</h3><p>A little something for every version of you.<br/>Let’s find your new favourite.</p><Button asChild><Link href="/#arrivals" onClick={()=>setCartOpen(false)}>Explore new arrivals<ArrowRight size={17}/></Link></Button></div>}
    </Dialog>
    <Dialog open={wishlistOpen} onOpenChange={setWishlistOpen} title="Your style, saved." description={`${wishlist.length} ${wishlist.length===1?"favourite":"favourites"}. All very you.`} sheet><div className="wishlist-list">{wishlist.length?products.filter(p=>wishlist.includes(p.id)).map(product=><div className="wishlist-line" key={product.id}><Link href={`/product/${product.slug}`} onClick={()=>setWishlistOpen(false)}><img src={product.image} alt={product.name} width={100} height={125}/></Link><div><span className="tiny-label">{product.category}</span><Link href={`/product/${product.slug}`} onClick={()=>setWishlistOpen(false)}>{product.name}</Link><strong>{money(product.price)}</strong><button className="text-link" onClick={()=>{setWishlistOpen(false);setQuickProduct({product,color:product.colors[0].name});}}>Choose size <Plus size={14}/></button></div><button className="icon-button" aria-label={`Remove ${product.name} from wishlist`} onClick={()=>toggleWishlist(product.id)}><Heart size={19} fill="currentColor" className="red-text"/></button></div>):<div className="empty-state"><div className="empty-icon"><Heart size={36} strokeWidth={1.25}/></div><h3>Love it? Save it.</h3><p>Tap the little heart on a style you love.<br/>We’ll keep it right here for you.</p><Button onClick={()=>setWishlistOpen(false)}>Find your favourites<ArrowRight size={17}/></Button></div>}</div></Dialog>
    <Dialog open={searchOpen} onOpenChange={setSearchOpen} title="What’s your next look?" className="search-dialog" description="Search styles, collections, and everyday favourites."><div className="search-field"><Search size={21}/><input autoFocus placeholder="Try ‘linen’, ‘kurta’ or ‘denim’…" aria-label="Search catalogue" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button onClick={()=>setQuery("")}>Clear</button>}</div><div className="search-suggestions"><span>TRY</span>{["Linen","Kurta","Denim","Kids"].map(term=><button key={term} onClick={()=>setQuery(term)}>{term}<ArrowRight size={12}/></button>)}</div><div className="search-result-label"><span>{query?`${results.length} results for “${query}”`:"A few things you might love"}</span><SlidersHorizontal size={15}/></div><div className="search-results">{results.slice(0,6).map(product=><Link key={product.id} href={`/product/${product.slug}`} onClick={()=>setSearchOpen(false)}><img src={product.image} alt={product.name} width={65} height={80}/><span><small>{product.category}</small><strong>{product.name}</strong><b>{money(product.price)}</b></span><ArrowRight size={18}/></Link>)}{!results.length&&<div className="empty-state"><Search size={32}/><h3>No matches. Yet.</h3><p>Try a category or a simpler search.</p><Button variant="outline" onClick={()=>setQuery("")}>See all styles</Button></div>}</div></Dialog>
    <Dialog open={!!quickProduct} onOpenChange={open=>{if(!open)setQuickProduct(null);}} title="Make it yours." description="Pick your colour and your perfect fit." className="quick-add-dialog">{quickProduct&&<QuickAdd key={quickProduct.product.id} product={quickProduct.product} initialColor={quickProduct.color}/>}</Dialog>
  </>;
}
