"use client";
import { useState } from "react";
import Link from "next/link";
import { animate, motion, useReducedMotion } from "motion/react";
import { ArrowRight, ArrowUp, ArrowUpRight, Camera, Check } from "lucide-react";
import { Brand } from "./navbar";
import { Dialog } from "./ui/dialog";
import { useShop } from "./shop-provider";
const policies:Record<string,{title:string;body:string[]}>={
  delivery:{title:"Delivery, without the guesswork.",body:["This website is a shopping prototype. All delivery availability and timelines are illustrative; no parcels are dispatched.","The prototype models complimentary delivery on orders of ₹999 or more. Below ₹999, a flat ₹49 delivery fee is shown. Illustrative estimates are 2–4 working days in the Siwan area and 5–7 working days elsewhere in India.","A store-pickup option is available to explore in the demo checkout. It does not reserve an item at the real store. Call +91 72900 36224 for current stock, delivery, and pickup information."]},
  returns:{title:"A little peace of mind.",body:["Products and orders on this site are for demonstration only, so there are no real purchases to return.","For purchases made at V-Mart Siwan, keep your original bill and product tags. Eligibility, timelines, and exclusions are governed by the policy printed on your store receipt.","Please call +91 72900 36224 or visit the Babunia More store for help with a real purchase. We do not publish unverified return promises."]},
  privacy:{title:"Your details stay yours.",body:["Your bag and saved styles are stored in this demo database, linked to an anonymous, essential browser cookie. No advertising trackers are used.","Style Studio preferences are saved to the same private session and can be deleted from the Studio. Recommendations use transparent catalogue rules, not AI profiling. Recently viewed styles are remembered only in this browser and can be cleared with the Clear history button.","Guest checkout details and prototype order records are stored to demonstrate a complete shopping flow. Use fictional details when trying the demo. Never enter real payment credentials; this site does not process money.","Newsletter emails are stored only when you submit the opt-in form. No marketing emails are sent by this prototype. To clear saved shopping choices, remove items from your bag and wishlist."]},
  about:{title:"Your city. Your style.",body:["V-Mart Siwan — Style in Motion is a fashion commerce concept designed for the Babunia More branch, with the supplied local contact details.","The catalogue, prices, availability, editorial photography, and online offers are illustrative. This prototype does not claim affiliation or operational integration with V-Mart Retail.","Visit the real store at Rajender Path, Babunia More, Chhapra Road, Pal Nagar, Siwan, Bihar 841226. Hours supplied: 10:00 AM to 10:00 PM. Phone: +91 72900 36224."]},
  help:{title:"Let’s find your answer.",body:["Shopping online? Choose a style, pick your size and colour, and add it to your bag. Hearts save your favourites. The filters help you browse by category, price and fit.","You can try our three-step guest checkout without an account. UPI, card, and netbanking options are simulations only. No money is charged, and no real order is placed with the store.","For actual store enquiries, sizing assistance or purchase support, please call +91 72900 36224 between 10:00 AM and 10:00 PM."]}
};
export function Footer() {
  const {setWishlistOpen,notify}=useShop();const [email,setEmail]=useState("");const [submitted,setSubmitted]=useState(false);const [sending,setSending]=useState(false);const [policy,setPolicy]=useState<string|null>(null);const reduced=useReducedMotion();
  async function subscribe(event:React.FormEvent){event.preventDefault();setSending(true);try{const response=await fetch("/api/newsletter",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSubmitted(true);notify(data.message);}catch(error){notify(error instanceof Error?error.message:"Could not subscribe. Please try again.");}finally{setSending(false);}}
  function backToTop(){if(reduced){window.scrollTo(0,0);return;}animate(window.scrollY,0,{duration:.8,ease:[.22,1,.36,1],onUpdate:value=>window.scrollTo(0,value)});}
  return <><footer className="site-footer"><div className="container"><div className="footer-top"><div><div className="eyebrow"><span className="small-line"/>STAY IN THE STYLE CIRCLE.</div><h2>GOOD THINGS.<br/>STRAIGHT TO YOUR INBOX<span>.</span></h2><p>Fresh drops, style notes, and a little something extra.</p></div><div className="newsletter-wrap">{submitted?<div className="newsletter-success" role="status"><Check size={24}/><div><strong>You’re in. Looking good.</strong><p>Welcome to the Siwan style circle.</p></div></div>:<form className="newsletter-form" onSubmit={subscribe}><label className="sr-only" htmlFor="newsletter-email">Your email address</label><input id="newsletter-email" type="email" placeholder="Your email address" autoComplete="email" value={email} required maxLength={180} onChange={e=>setEmail(e.target.value)}/><motion.button whileHover={{x:3}} type="submit" aria-label="Join the style circle" disabled={sending}>{sending?"…":<ArrowRight size={21}/>}</motion.button></form>}<p>By joining, you agree to our <button onClick={()=>setPolicy("privacy")}>Privacy Policy</button>.<br/>A demo style circle. No spam. No emails sent.</p></div></div>
      <div className="footer-main"><div className="footer-brand"><Brand/><p>Everyday fashion. Standout style.<br/>Your city. Your people. Your V-Mart.</p><span className="footer-hindi">अंदाज़ आपका। साथ हमारा।</span><div className="social-links"><a href="https://www.instagram.com/vmartretail/" target="_blank" rel="noopener noreferrer" aria-label="V-Mart on Instagram"><Camera size={19}/></a><a href="https://www.facebook.com/VmartRetail/" target="_blank" rel="noopener noreferrer" aria-label="V-Mart on Facebook"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M14 21v-8h2.8l.4-3H14V8.1c0-.9.3-1.5 1.6-1.5h1.7V3.9a22 22 0 0 0-2.5-.1c-2.5 0-4.1 1.5-4.1 4.3V10H8v3h2.7v8H14Z"/></svg></a><a href="tel:+917290036224" aria-label="Call V-Mart Siwan"><ArrowUpRight size={20}/></a></div></div><div className="footer-link-column"><h3>FIND YOUR STYLE</h3><Link href="/?category=Men#arrivals">Men</Link><Link href="/?category=Women#arrivals">Women</Link><Link href="/?category=Kids#arrivals">Kids & little ones</Link><Link href="/#arrivals">New arrivals</Link><Link href="/#campaign">The celebration edit</Link></div><div className="footer-link-column"><h3>HERE TO HELP</h3><button onClick={()=>setPolicy("help")}>Customer care</button><button onClick={()=>setPolicy("delivery")}>Delivery & store pickup</button><button onClick={()=>setPolicy("returns")}>Returns & exchanges</button><button onClick={()=>setWishlistOpen(true)}>Your wishlist</button><button onClick={()=>setPolicy("privacy")}>Privacy policy</button></div><div className="footer-store"><h3>COME SAY HELLO</h3><p>Rajender Path, Babunia More<br/>Chhapra Road, Siwan<br/>Bihar 841226</p><a href="tel:+917290036224">+91 72900 36224</a><span>10:00 AM – 10:00 PM, every day</span><Link href="/#visit">Find our store<ArrowUpRight size={14}/></Link></div></div>
      <div className="footer-bottom"><span>© {new Date().getFullYear()} V-Mart Siwan. Style in Motion.</span><button onClick={()=>setPolicy("about")}>Commerce concept · Prototype, not a live store</button><motion.button className="back-to-top" whileHover={{y:-3}} onClick={backToTop}>BACK TO TOP <ArrowUp size={15}/></motion.button></div><a href="https://dynamicdevelopments.vercel.app/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center text-sm underline underline-offset-4">Developed by Dynamic Developments</a><div className="footer-watermark" aria-hidden="true">STYLE IN MOTION.</div>
    </div></footer><Dialog open={!!policy} onOpenChange={open=>{if(!open)setPolicy(null);}} title={policy?policies[policy].title:""} description="V-Mart Siwan — a little clarity goes a long way." className="policy-dialog"><div className="policy-content">{policy&&policies[policy].body.map(text=><p key={text}>{text}</p>)}<a className="text-link" href="tel:+917290036224">Talk to the Siwan store <ArrowUpRight size={16}/></a></div></Dialog></>;
}
