"use client";
import { useMemo, useState, useTransition } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, ArrowUpRight, SlidersHorizontal, X, Sparkles, BadgeIndianRupee, MapPin, Shirt, RotateCcw } from "lucide-react";
import type { Product } from "@/lib/types";
import { CATEGORIES } from "@/lib/catalog";
import { Hero } from "./hero";
import { Reveal, scrollToSection } from "./motion-utils";
import { ProductCard } from "./product-card";
import { StoreSection } from "./store-section";
import { ShopTheLook } from "./shop-the-look";
import { StudioInvitation } from "./style-studio";
import { RecentlyViewed } from "./recently-viewed";
import { useShop } from "./shop-provider";
import { Button } from "./ui/button";
export function HomePage({ initialProducts }: { initialProducts: Product[] }) {
  const shop = useShop(); const { t } = shop; const products = shop.ready ? shop.products : initialProducts;
  const router = useRouter(); const searchParams = useSearchParams(); const [isFiltering, startTransition] = useTransition();
  const rawCategory = searchParams.get("category"); const category = ["Men", "Women", "Kids", "Infants"].includes(rawCategory ?? "") ? rawCategory! : "All";
  const rawBudget = searchParams.get("budget"); const budget = ["499", "799", "999", "999+"].includes(rawBudget ?? "") ? rawBudget! : "all";
  const size = searchParams.get("size") || "all"; const sort = searchParams.get("sort") || "featured";
  const showAll = searchParams.get("view") === "all" || category !== "All" || budget !== "all" || size !== "all" || sort !== "featured";
  const [filtersOpen, setFiltersOpen] = useState(budget !== "all" || size !== "all" || sort !== "featured");
  const sizes = [...new Set(products.filter(product => category === "All" || product.category === category).flatMap(product => product.sizes))];
  const filtered = useMemo(() => {
    let result = products.filter(product => (category === "All" || product.category === category) && (budget === "all" || (budget === "999+" ? product.price >= 999 : product.price < Number(budget))) && (size === "all" || product.variants.some(variant => variant.size === size && variant.stock > 0)));
    if (sort === "low") result = [...result].sort((a, b) => a.price - b.price); if (sort === "high") result = [...result].sort((a, b) => b.price - a.price); return result;
  }, [products, category, budget, size, sort]);
  const display = showAll ? filtered : filtered.slice(0, 4);
  function updateFilters(changes: Record<string, string | null>) { const next = new URLSearchParams(searchParams.toString()); Object.entries(changes).forEach(([key, value]) => { if (value === null || value === "all" || value === "featured") next.delete(key); else next.set(key, value); }); startTransition(() => router.replace(`${next.size ? `/?${next.toString()}` : "/"}#arrivals`, { scroll: false })); }
  function selectCategory(value: string, scroll = false) { updateFilters({ category: value === "All" ? null : value, budget: null, size: null, sort: null, view: value === "All" ? null : "all" }); if (scroll) setTimeout(() => scrollToSection("arrivals"), 50); }
  function selectBudget(value: string) { updateFilters({ category: null, budget: value, size: null, sort: null, view: "all" }); setFiltersOpen(true); setTimeout(() => scrollToSection("arrivals"), 50); }
  function reset() { startTransition(() => router.replace("/#arrivals", { scroll: false })); }
  return <main id="main-content"><Hero/>
    <div className="benefits-strip"><div className="container benefits-inner"><div><Sparkles size={18}/><span>FRESH STYLES. EVERY SEASON.</span></div><span className="benefit-separator"/><div><BadgeIndianRupee size={19}/><span>BIG STYLE. REAL VALUE.</span></div><span className="benefit-separator"/><div><Shirt size={18}/><span>FOR THE WHOLE FAMILY.</span></div><span className="benefit-separator"/><div><MapPin size={18}/><span>YOUR SIWAN. YOUR STORE.</span></div></div></div>
    <section className="categories-section section-space" id="categories"><div className="container"><Reveal className="section-heading"><div><div className="eyebrow"><span className="small-line"/>{t("A STYLE FOR EVERY STORY", "हर कहानी का अपना स्टाइल")}</div><h2>{t("EVERYONE’S INVITED.", "सबके लिए कुछ ख़ास।")}</h2></div><div className="section-heading-right"><p>Different people. A thousand possibilities.<br/>Find the one that feels like you.</p><button className="text-link" onClick={() => { reset(); scrollToSection("arrivals"); }}>Explore all<ArrowUpRight size={17}/></button></div></Reveal><div className="categories-grid edition-categories">{CATEGORIES.map((item, index) => <Reveal key={item.name} delay={index * .05}><motion.button className="category-card" onClick={() => selectCategory(item.name, true)} whileHover={{ y: -4 }} whileTap={{ scale: .99 }} transition={{ type: "spring", stiffness: 240, damping: 24 }} aria-label={`Shop ${item.name}`}><motion.img src={item.image} alt={`${item.name}'s new-season collection`} loading="lazy" width={600} height={800} whileHover={{ scale: 1.04 }} transition={{ duration: .5 }}/><div className="category-shade"/><span className="category-number">0{index + 1} / THE COLLECTION</span><div className="category-bottom"><div><h3>{t(item.name.toUpperCase(), ["पुरुष", "महिलाएं", "बच्चे", "शिशु"][index])}</h3><p>{item.caption}</p></div><span className="category-arrow"><ArrowUpRight size={22}/></span></div><span className="category-piece-count">{products.filter(product => product.category === item.name).length} styles to make your own</span></motion.button></Reveal>)}</div><Reveal className="studio-invitation-wrap"><StudioInvitation/></Reveal></div></section>
    <section className="arrivals-section section-space" id="arrivals"><div className="container"><Reveal className="section-heading"><div><div className="eyebrow"><span className="small-line"/>{t("JUST LANDED. ALREADY LOVED.", "नए स्टाइल। नया प्यार।")}</div><h2>{t("YOUR NEXT FAVOURITES.", "आपके नए पसंदीदा।")}</h2></div><div className="section-heading-right"><p>Fresh in store. Ready for your rotation.</p><span className="collection-counter"><span className="status-dot"/>{products.length.toString().padStart(2, "0")} NEW-SEASON FINDS</span></div></Reveal>
      <div className="filter-bar"><div className="category-tabs" role="group" aria-label="Filter by category">{["All", "Men", "Women", "Kids", "Infants"].map((cat, index) => <button key={cat} className={category === cat ? "active" : ""} aria-pressed={category === cat} onClick={() => selectCategory(cat)}>{t(cat === "All" ? "All styles" : cat, ["सभी", "पुरुष", "महिलाएं", "बच्चे", "शिशु"][index])}{category === cat && <motion.span layoutId="category-pill" className="category-pill" transition={{ type: "spring", stiffness: 400, damping: 32 }}/>}</button>)}</div><div className="edition-filter-controls"><span className="edition-result-count" aria-live="polite">{filtered.length} styles</span><button className={`filter-toggle ${filtersOpen ? "active" : ""}`} aria-label="Filters" aria-expanded={filtersOpen} onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={17}/><span>Filters & sort</span>{(budget !== "all" || size !== "all" || sort !== "featured") && <span className="filter-active-dot"/>}</button></div></div>
      <AnimatePresence>{filtersOpen && <motion.div className="expanded-filters" initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}><label>Price<select value={budget} onChange={event => updateFilters({ budget: event.target.value, view: "all" })}><option value="all">All prices</option><option value="499">Under ₹499</option><option value="799">Under ₹799</option><option value="999">Under ₹999</option><option value="999+">₹999 and above</option></select></label><label>Size<select value={size} onChange={event => updateFilters({ size: event.target.value, view: "all" })}><option value="all">All sizes</option>{sizes.map(item => <option key={item} value={item}>{item}</option>)}</select></label><label>Sort by<select value={sort} onChange={event => updateFilters({ sort: event.target.value, view: "all" })}><option value="featured">Featured picks</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label><button className="text-link" onClick={reset}>Reset filters<RotateCcw size={14}/></button><span className="filter-result-count">YOUR NEXT LOOK, REFINED.</span></motion.div>}</AnimatePresence>
      {(budget !== "all" || size !== "all" || sort !== "featured") && <div className="active-filter-chips" aria-label="Applied filters">{budget !== "all" && <button onClick={() => updateFilters({ budget: null })} aria-label="Remove price filter">{budget === "999+" ? "₹999 and above" : `Under ₹${budget}`}<X size={12}/></button>}{size !== "all" && <button onClick={() => updateFilters({ size: null })} aria-label="Remove size filter">Size {size}<X size={12}/></button>}{sort !== "featured" && <button onClick={() => updateFilters({ sort: null })} aria-label="Remove sort order">Price: {sort === "low" ? "low to high" : "high to low"}<X size={12}/></button>}</div>}
      <motion.div layout className="product-grid" aria-busy={isFiltering}><AnimatePresence mode="popLayout">{display.map(product => <ProductCard key={product.id} product={product}/>)}</AnimatePresence></motion.div>{!filtered.length && <div className="empty-state filter-empty"><SlidersHorizontal size={32}/><h3>A new combination, perhaps?</h3><p>No styles match these filters. Try a different size or budget.</p><Button variant="dark" onClick={reset}>Reset filters</Button></div>}
      <div className="arrivals-footer"><span>A LITTLE REFRESH GOES A LONG WAY.</span>{filtered.length > 4 && <Button variant="outline" onClick={() => showAll ? reset() : updateFilters({ view: "all" })}>{showAll ? "Show the highlights" : `Explore all ${filtered.length} styles`}<ArrowRight size={17}/></Button>}<span>GOOD FINDS. GREAT FEELING.</span></div><RecentlyViewed/>
    </div></section>
    <ShopTheLook products={products}/>
    <section id="campaign" className="campaign-section"><motion.div className="campaign-image" initial={{ scale: 1.05 }} whileInView={{ scale: 1 }} viewport={{ once: true }} transition={{ duration: 1.4 }} style={{ backgroundImage: "url('/images/festive-campaign.jpg')" }}/><div className="campaign-shade"/><div className="container campaign-content"><Reveal><div className="eyebrow"><Sparkles size={15}/>EVERY LITTLE MOMENT DESERVES A LITTLE EXTRA.</div><h2>DRESSED FOR<br/>THE GOOD TIMES<span>.</span></h2><p>From family get-togethers to your next big celebration.<br/>A fresh take on festive, made for you.</p><motion.button className="button button-light" whileHover={{ y: -3 }} whileTap={{ scale: .97 }} onClick={() => selectCategory("Women", true)}>Find your festive fit<ArrowUpRight size={18}/></motion.button></Reveal><span className="campaign-caption">THE CELEBRATION EDIT<span>V-MART / SIWAN</span></span></div></section>
    <section className="budget-section section-space" id="budget"><div className="container"><Reveal className="section-heading"><div><div className="eyebrow"><span className="small-line"/>LOOK GOOD. FEEL EVEN BETTER.</div><h2>{t("BIG STYLE. YOUR BUDGET.", "बड़ा स्टाइल। आपके बजट में।")}</h2></div><p className="section-description">A great look doesn’t need a big price tag.<br/>Your next find is right in your range.</p></Reveal><div className="budget-grid">{[{ amount: "499", label: "THE LITTLE WINS", description: "Small price. Instant favourites." }, { amount: "799", label: "EVERYDAY UPGRADES", description: "More of what you love." }, { amount: "999", label: "STYLE WITHOUT LIMITS", description: "A whole lot of possibilities." }, { amount: "999+", label: "A LITTLE EXTRA", description: "Go on. Treat your wardrobe." }].map((item, index) => { const count = products.filter(product => item.amount === "999+" ? product.price >= 999 : product.price < Number(item.amount)).length; return <Reveal delay={index * .05} key={item.amount}><motion.button className={`budget-card budget-card-${index}`} whileHover={{ y: -4 }} whileTap={{ scale: .98 }} onClick={() => selectBudget(item.amount)}><span className="budget-overline">{item.label}</span><div className="budget-price">{item.amount !== "999+" && <span>UNDER</span>}<strong>₹{item.amount}</strong></div><p>{item.description}</p><div className="budget-bottom"><span>{count} styles to discover</span><span><ArrowUpRight size={19}/></span></div><span className="budget-decoration" aria-hidden="true">₹</span></motion.button></Reveal>; })}</div></div></section>
    <StoreSection/>
  </main>;
}
