"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { MapPin, Search, Heart, ShoppingBag, Menu, ArrowUpRight, ArrowRight, Sparkles, Command } from "lucide-react";
import { AnimatePresence, motion, useScroll, useSpring } from "motion/react";
import { useShop } from "./shop-provider";
import { useDiscovery } from "./discovery-provider";
import { Dialog } from "./ui/dialog";
import { scrollToSection } from "./motion-utils";
export function Brand({ dark = false }: { dark?: boolean }) { return <Link href="/" className={`brand ${dark ? "brand-dark" : ""}`} aria-label="V-Mart Siwan home"><span className="brand-symbol"><svg width="22" height="25" viewBox="0 0 22 25" fill="none" aria-hidden="true"><path d="M2 4L10.5 21L20 2M7 4L11 12.5L16 2" stroke="currentColor" strokeWidth="3.3" strokeLinecap="square"/></svg></span><span className="brand-word">V-MART<span className="branch-badge">SIWAN</span></span></Link>; }
export function Navbar() {
  const { cart, wishlist, setCartOpen, setWishlistOpen, setSearchOpen, setQuickProduct, language, setLanguage, t } = useShop();
  const { setStudioOpen, setBundle } = useDiscovery();
  const [menu, setMenu] = useState(false); const pathname = usePathname(); const router = useRouter();
  const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 180, damping: 35 });
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const links = [{ name: "Men", hi: "पुरुष", target: "arrivals" }, { name: "Women", hi: "महिलाएं", target: "arrivals" }, { name: "Kids", hi: "बच्चे", target: "arrivals" }, { name: "Offers", hi: "ऑफ़र", target: "campaign" }];
  useEffect(() => { function shortcut(event: KeyboardEvent) { const target = event.target; const typing = target instanceof HTMLElement && (target.isContentEditable || ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName)); if (((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") || (event.key === "/" && !typing && !event.metaKey && !event.ctrlKey)) { event.preventDefault(); setMenu(false); setStudioOpen(false); setBundle(null); setCartOpen(false); setWishlistOpen(false); setQuickProduct(null); setSearchOpen(true); } } window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, [setStudioOpen, setBundle, setCartOpen, setWishlistOpen, setQuickProduct, setSearchOpen]);
  function navigate(event: React.MouseEvent, name: string, target: string) { setMenu(false); if (pathname === "/") { event.preventDefault(); router.push(name === "Offers" ? "/#campaign" : `/?category=${name}#arrivals`, { scroll: false }); setTimeout(() => scrollToSection(target), 80); } }
  return <>
    <div className="announcement"><span>EVERYDAY FASHION. EXTRAORDINARY YOU.</span><button className="announcement-studio" onClick={() => setStudioOpen(true)}><Sparkles size={11}/>{t("Introducing your personal Style Studio", "आपके लिए खास — स्टाइल स्टूडियो")}<ArrowRight size={12}/></button><span className="announcement-right">SIWAN, THIS IS YOUR MOMENT.</span></div>
    <header className="site-header"><nav className="nav-inner" aria-label="Main navigation"><Brand/><Link href="/#visit" className="location-pill"><MapPin size={14}/><span>Babunia More, Siwan</span><span className="status-dot"/></Link><div className="desktop-nav">{links.map(link => <Link key={link.name} href={link.name === "Offers" ? "/#campaign" : `/?category=${link.name}#arrivals`} onClick={event => navigate(event, link.name, link.target)} className={link.name === "Offers" ? "offer-link" : ""}>{t(link.name, link.hi)}{link.name === "Offers" && <span className="tiny-red-dot"/>}</Link>)}</div><button className="nav-studio-button" aria-label="Open Style Studio" onClick={() => setStudioOpen(true)}><Sparkles size={14}/><span>Style Studio</span><span className="nav-studio-new">NEW</span></button><div className="nav-actions"><div className="language-toggle" aria-label="Website language"><button onClick={() => setLanguage("en")} aria-pressed={language === "en"} className={language === "en" ? "active" : ""}>EN</button><span>/</span><button onClick={() => setLanguage("hi")} aria-pressed={language === "hi"} className={language === "hi" ? "active" : ""}>हिंदी</button></div><span className="nav-divider"/><button className="icon-button nav-search" aria-label="Search products" title="Search products · ⌘/Ctrl K" onClick={() => setSearchOpen(true)}><Search size={20}/><span className="search-key-hint" aria-hidden="true">⌘ K</span></button><button className="icon-button wishlist-nav" aria-label={`Wishlist, ${wishlist.length} saved items`} onClick={() => setWishlistOpen(true)}><Heart size={20}/>{wishlist.length > 0 && <span className="small-badge">{wishlist.length}</span>}</button><button className="icon-button cart-button" aria-label={`Open shopping bag, ${count} items`} onClick={() => setCartOpen(true)}><ShoppingBag size={20}/><AnimatePresence mode="popLayout"><motion.span key={count} className="cart-count" initial={{ scale: .5 }} animate={{ scale: 1 }} transition={{ type: "spring", stiffness: 450, damping: 18 }}>{count}</motion.span></AnimatePresence></button><button className="icon-button mobile-menu-button" aria-label="Open navigation menu" onClick={() => setMenu(true)}><Menu size={22}/></button></div></nav><motion.div className="nav-reading-progress" style={{ scaleX: progress }} aria-hidden="true"/></header>
    <Dialog open={menu} onOpenChange={setMenu} title="Find your next look." className="mobile-menu" description="Fashion for every version of you."><div className="mobile-menu-links">{links.map((link, index) => <motion.div key={link.name} initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }}><Link href={link.name === "Offers" ? "/#campaign" : `/?category=${link.name}#arrivals`} onClick={event => navigate(event, link.name, link.target)}><span><small>0{index + 1}</small>{t(link.name, link.hi)}</span><ArrowUpRight/></Link></motion.div>)}</div><button className="mobile-studio-entry" onClick={() => { setMenu(false); setStudioOpen(true); }}><Sparkles size={20}/><span><strong>A personal edit. All you.</strong><small>Step inside the Style Studio</small></span><ArrowUpRight size={19}/></button><button className="mobile-wishlist" onClick={() => { setMenu(false); setWishlistOpen(true); }}><Heart size={20}/>Your wishlist<span>{wishlist.length}</span></button><Link href="/#visit" onClick={() => setMenu(false)} className="mobile-location"><MapPin size={19}/><span>Your neighbourhood. Your runway.<br/><strong>Babunia More, Siwan</strong></span></Link></Dialog>
  </>;
}
