"use client";
import { forwardRef, useState } from "react";
import Link from "next/link";
import { Heart, Plus, ArrowUpRight } from "lucide-react";
import { motion } from "motion/react";
import type { Product } from "@/lib/types";
import { money } from "@/lib/types";
import { useShop } from "./shop-provider";
export const ProductCard = forwardRef<HTMLElement, { product: Product }>(function ProductCard({ product }, ref) {
  const { wishlist, toggleWishlist, setQuickProduct, pending, t } = useShop(); const [color, setColor] = useState(product.colors[0].name); const saved = wishlist.includes(product.id); const available = product.variants.some(variant => variant.stock > 0);
  return <motion.article ref={ref} layout className="product-card edition-product-card" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: .96 }} transition={{ duration: .28 }}>
    <motion.div className="product-image-wrap" initial="rest" whileHover="hover" whileFocus="hover"><Link href={`/product/${product.slug}`} className="product-image-link" aria-label={`View ${product.name}`}><motion.img src={product.image} alt={product.name} loading="lazy" decoding="async" width={600} height={800} variants={{ rest: { scale: 1 }, hover: { scale: 1.025 } }} transition={{ duration: .55 }}/>{product.images[1] && <motion.img className="product-detail-preview" src={product.images[1]} alt="" aria-hidden="true" loading="lazy" decoding="async" width={600} height={800} variants={{ rest: { opacity: 0, scale: 1.04 }, hover: { opacity: 1, scale: 1 } }} transition={{ duration: .4 }}/>}</Link>{product.badge && <span className="product-badge">{available ? product.badge : "CURRENTLY UNAVAILABLE"}</span>}<motion.button whileTap={{ scale: .8 }} className={`wishlist-button ${saved ? "is-saved" : ""}`} aria-label={`${saved ? "Remove" : "Save"} ${product.name} ${saved ? "from" : "to"} wishlist`} aria-pressed={saved} disabled={pending} onClick={() => toggleWishlist(product.id)}><Heart size={18} fill={saved ? "currentColor" : "none"}/></motion.button><motion.span className="product-detail-caption" aria-hidden="true" variants={{ rest: { opacity: 0 }, hover: { opacity: 1 } }}>IT’S ALL IN THE DETAILS.<span>02 / 02</span></motion.span><motion.button className="quick-add" variants={{ rest: { opacity: 0, y: 12 }, hover: { opacity: 1, y: 0 } }} transition={{ type: "spring", stiffness: 330, damping: 25 }} whileTap={{ scale: .98 }} disabled={!available} onClick={() => setQuickProduct({ product, color })}>{available ? t("Quick add", "बैग में जोड़ें") : "Currently unavailable"}<Plus size={17}/></motion.button></motion.div>
    <div className="product-meta"><div className="product-meta-top"><span>{product.category} / EVERYDAY EDIT</span><div className="swatches">{product.colors.map(item => <button key={item.name} title={item.name} aria-label={`${product.name}, ${item.name}`} aria-pressed={color === item.name} className={color === item.name ? "selected" : ""} onClick={() => setColor(item.name)}><span style={{ background: item.hex }}/></button>)}</div></div><Link href={`/product/${product.slug}`} className="product-name">{product.name}<ArrowUpRight size={16}/></Link><div className="product-price"><strong>{money(product.price)}</strong><del>{money(product.originalPrice)}</del><span>{Math.round((1 - product.price / product.originalPrice) * 100)}% off</span></div></div>
  </motion.article>;
});
