"use client";
import { useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { ArrowRight, ArrowUpRight, Check, Layers, Plus, X } from "lucide-react";
import { LOOK_BUNDLES } from "@/lib/discovery";
import { money, type Product } from "@/lib/types";
import { useShop } from "./shop-provider";
import { useDiscovery } from "./discovery-provider";
import { Reveal } from "./motion-utils";
import { Button } from "./ui/button";
export function ShopTheLook({ products }: { products: Product[] }) {
  const { setQuickProduct, t } = useShop(); const { setBundle } = useDiscovery();
  const [lookIndex, setLookIndex] = useState(0); const [hotspot, setHotspot] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null); const reduced = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] }); const y = useTransform(scrollYProgress, [0, 1], [-14, 14]);
  const look = LOOK_BUNDLES[lookIndex];
  const pieces = look.productIds.flatMap(id => { const product = products.find(p => p.id === id); return product ? [product] : []; });
  const total = pieces.reduce((sum, product) => sum + product.price, 0);
  const spots = lookIndex === 0 ? [{ left: "66%", top: "38%" }, { left: "34%", top: "66%" }] : [{ left: "48%", top: "44%" }, { left: "80%", top: "81%" }];
  return <section className="lookbook-section section-space edition-lookbook" id="lookbook"><div className="container"><div className="lookbook-section-top"><span className="eyebrow"><span className="small-line"/>NOT JUST PIECES. A WHOLE PERSPECTIVE.</span><span>THE STYLE FILES / 01 — 02</span></div><div className="lookbook-layout" ref={ref}>
    <Reveal className={`lookbook-photo-wrap lookbook-photo-${lookIndex}`}><AnimatePresence initial={false}><motion.img key={look.image} className="lookbook-photo" src={look.image} alt={lookIndex === 0 ? "Effortless linen and wide-leg denim, styled together in a sunlit courtyard" : "An olive textured tee, the foundation of an easy weekend look"} width={1056} height={792} loading="lazy" style={{ y: reduced ? 0 : y, scale: 1.06 }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .45 }}/></AnimatePresence><div className="lookbook-photo-label"><span>{look.title.toUpperCase()}</span><span>LOOK / 0{lookIndex + 1}</span></div>{lookIndex === 1 && <motion.div className="lookbook-inset-product" initial={{ opacity: 0, rotate: 4, y: reduced ? 0 : 15 }} animate={{ opacity: 1, rotate: 4, y: 0 }}><img src="/images/product-sneakers.jpg" alt="Cream court sneakers, paired with the weekend tee" width={170} height={210}/><span>THE FINISHING TOUCH.</span></motion.div>}{pieces.map((product, index) => <div key={product.id} className="look-hotspot" style={spots[index]} onKeyDown={event => { if (event.key === "Escape") setHotspot(null); }}><motion.button whileHover={{ scale: 1.08 }} whileTap={{ scale: .94 }} className="hotspot-dot" aria-label={`Shop ${product.name}`} aria-expanded={hotspot === product.id} onClick={() => setHotspot(hotspot === product.id ? null : product.id)}>{hotspot === product.id ? <X size={19}/> : <Plus size={19}/>}</motion.button><AnimatePresence>{hotspot === product.id && <motion.div role="group" aria-label={product.name} className="hotspot-product" initial={{ opacity: 0, y: reduced ? 0 : 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: reduced ? 0 : 5 }}><img src={product.image} alt={product.name} width={55} height={72}/><div><strong>{product.name}</strong><span>{money(product.price)}</span><button onClick={() => setQuickProduct({ product, color: product.colors[0].name })}>Choose your fit<ArrowRight size={12}/></button></div></motion.div>}</AnimatePresence></div>)}<span className="lookbook-image-hint"><Plus size={14}/>Tap a piece. Make it yours.</span><span className="lookbook-photo-index" aria-hidden="true">0{lookIndex + 1}</span></Reveal>
    <Reveal className="lookbook-copy" delay={.1}><div className="lookbook-tabs" role="group" aria-label="Choose an editorial look">{LOOK_BUNDLES.map((item, index) => <button key={item.id} aria-pressed={lookIndex === index} className={lookIndex === index ? "selected" : ""} onClick={() => { setLookIndex(index); setHotspot(null); }}><span>0{index + 1}</span>{index === 0 ? "The everyday duo" : "Weekend uniform"}{lookIndex === index && <motion.span className="lookbook-tab-underline" layoutId="lookbook-tab"/>}</button>)}</div><div className="eyebrow">{lookIndex === 0 ? "LESS EFFORT. MORE YOU." : "CLOCKED OUT. DIALED IN."}</div><AnimatePresence mode="wait"><motion.div key={lookIndex} initial={{ opacity: 0, y: reduced ? 0 : 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: .24 }}><h2>{lookIndex === 0 ? <>{t("OFF DUTY.", "हर दिन।")}<br/>{t("ON POINT.", "हर अंदाज़।")}</> : <>WEEKEND.<br/>ON REPEAT.</>}<span className="red-text">*</span></h2><p className="lookbook-serif">{lookIndex === 0 ? "No occasion needed." : "Good plans. Better basics."}</p><p className="section-description">{look.description}</p></motion.div></AnimatePresence><div className="lookbook-products">{pieces.map((product, index) => <button key={product.id} onClick={() => setQuickProduct({ product, color: product.colors[0].name })}><span className="look-number">0{index + 1}</span><span><strong>{product.name}</strong><small>{money(product.price)}<span>· {product.colors.length} {product.colors.length === 1 ? "colour" : "colours"}</span></small></span><Plus size={18}/></button>)}</div><div className="lookbook-buy-row"><Button variant="dark" onClick={() => setBundle(look)}>Build this look<Layers size={17}/></Button><span>{pieces.length} pieces from <strong>{money(total)}</strong></span></div><span className="lookbook-footnote"><Check size={12}/>Your sizes. Your colours. One easy add.</span></Reveal>
  </div></div></section>;
}
