"use client";
import { useCallback, useEffect, useState } from "react";
import useEmblaCarousel from "embla-carousel-react";
import { ArrowLeft, ArrowRight, ArrowUpRight, MapPin, Phone, Clock, Navigation, Store, Check } from "lucide-react";
import { motion } from "motion/react";
import { STORE_ADDRESS, MAP_QUERY, MAP_URL } from "@/lib/catalog";
import { Reveal } from "./motion-utils";
import { Button } from "./ui/button";
import { useShop } from "./shop-provider";
export function StoreSection() {
  const {t}=useShop();const [emblaRef,emblaApi]=useEmblaCarousel({loop:true});const [selected,setSelected]=useState(0);const [openNow,setOpenNow]=useState<boolean|null>(null);
  const update=useCallback(()=>setSelected(emblaApi?.selectedScrollSnap()??0),[emblaApi]);
  useEffect(()=>{if(!emblaApi)return;emblaApi.on("select",update);return()=>{emblaApi.off("select",update);};},[emblaApi,update]);
  useEffect(()=>{function updateHours(){const hour=Number(new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",hour:"2-digit",hourCycle:"h23"}).format(new Date()));setOpenNow(hour>=10&&hour<22);}updateHours();const timer=setInterval(updateHours,60000);return()=>clearInterval(timer);},[]);
  const photos=[{src:"/images/editorial-look.jpg",title:"Meet your everyday favourites.",subtitle:"THE EVERYDAY EDIT"},{src:"/images/category-kids.jpg",title:"A little something for everyone.",subtitle:"THE FAMILY EDIT"},{src:"/images/festive-campaign.jpg",title:"Make every moment a little more you.",subtitle:"THE CELEBRATION EDIT"}];
  return <section className="store-section section-space" id="visit"><div className="container"><div className="store-layout"><Reveal className="store-copy"><div className="eyebrow"><span className="small-line"/>{t("ONLINE INSPIRATION. IN-STORE DISCOVERY.","ऑनलाइन पसंद करें। स्टोर में मिलें।")}</div><h2>{t("YOUR NEIGHBOURHOOD.","आपका शहर।")}<br/>{t("YOUR RUNWAY.","आपका स्टाइल।")}</h2><p className="store-intro">Some things are even better in person.<br/>Come find your next favourite at V-Mart Siwan.</p><div className="store-details"><div><MapPin size={19}/><div><strong>V-Mart, Babunia More</strong><p>{STORE_ADDRESS}</p></div></div><div><Clock size={19}/><div><strong>10:00 AM – 10:00 PM <span className={`open-status ${openNow===false?"closed":""}`}>{openNow===null?"DAILY":openNow?"OPEN NOW":"OPENS AT 10 AM"}</span></strong><p>A little style, every day of the week.</p></div></div><div><Phone size={18}/><div><a href="tel:+917290036224">+91 72900 36224</a><p>Questions? Your Siwan team is a call away.</p></div></div></div><div className="store-actions"><Button variant="dark" asChild><a href={MAP_URL} target="_blank" rel="noopener noreferrer">Get directions<Navigation size={16}/></a></Button><a className="text-link" href="tel:+917290036224">Call the store<ArrowUpRight size={16}/></a></div><p className="store-hindi">आपका अपना फ़ैशन डेस्टिनेशन। <span>मिलते हैं V-Mart में।</span></p></Reveal>
      <Reveal className="store-map-wrap" delay={.12}><div className="map-card"><iframe title="Find V-Mart Siwan at Babunia More on Google Maps" src={`https://maps.google.com/maps?q=${encodeURIComponent(MAP_QUERY)}&t=&z=15&ie=UTF8&iwloc=&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="map-location-card" href={MAP_URL} target="_blank" rel="noopener noreferrer"><span className="map-brand"><Store size={22}/></span><span><strong>V-Mart Siwan</strong><small>Babunia More · Your style stop</small></span><ArrowUpRight size={21}/></a></div><div className="store-map-caption"><span><MapPin size={12}/> SIWAN, BIHAR · 841226</span><span>DROP BY. TRY ON. WALK OUT YOU.</span></div></Reveal></div>
      <Reveal className="store-gallery"><div className="store-gallery-label"><span className="eyebrow">A GLIMPSE OF THE V-MART EDIT</span><span>Illustrative campaign gallery · not store photography</span></div><div className="gallery-viewport" ref={emblaRef}><div className="gallery-track">{photos.map((photo,i)=><div className="gallery-slide" key={photo.src}><img src={photo.src} alt={photo.title+" — illustrative campaign imagery"} loading="lazy" width={1200} height={400}/><div className="gallery-image-shade"/><div className="gallery-slide-copy"><span>{photo.subtitle}</span><h3>{photo.title}</h3><span className="gallery-slide-index">0{i+1} / 03</span></div></div>)}</div></div><div className="gallery-controls"><div className="gallery-dots">{photos.map((_,i)=><button aria-label={`Go to gallery image ${i+1}`} aria-current={selected===i?"true":undefined} key={i} onClick={()=>emblaApi?.scrollTo(i)}><span className={selected===i?"active":""}/></button>)}</div><div><motion.button whileTap={{scale:.92}} className="icon-button" onClick={()=>emblaApi?.scrollPrev()} aria-label="Previous gallery image"><ArrowLeft size={19}/></motion.button><motion.button whileTap={{scale:.92}} className="icon-button" onClick={()=>emblaApi?.scrollNext()} aria-label="Next gallery image"><ArrowRight size={19}/></motion.button></div></div></Reveal>
    </div></section>;
}
