"use client";
import { useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCheck, Heart, LayoutGrid, RotateCcw, Sparkles, Plus, ShieldCheck, SlidersHorizontal, LoaderCircle } from "lucide-react";
import { useShop } from "./shop-provider";
import { useDiscovery } from "./discovery-provider";
import { Dialog } from "./ui/dialog";
import { Button } from "./ui/button";
import { STYLE_BUDGETS, STYLE_CATEGORIES, STYLE_MOODS, type StylePreferences } from "@/lib/discovery";
import { CATEGORIES } from "@/lib/catalog";
import { money } from "@/lib/types";

function StudioExperience() {
  const { products, wishlist, toggleWishlist, setQuickProduct, pending } = useShop();
  const { profile, profileReady, profileError, saving, savePreferences, clearPreferences, loadProfile, setStudioOpen } = useDiscovery();
  const [answers, setAnswers] = useState<StylePreferences>(profile.preferences ?? { category: "Everyone", mood: "everyday", budget: 999 });
  const [step, setStep] = useState(profile.preferences ? 3 : 0);
  const reduced = useReducedMotion();
  const matching = profile.picks.flatMap(pick => { const product = products.find(p => p.id === pick.productId); return product ? [{ product, reason: pick.reason }] : []; });
  const activeMood = STYLE_MOODS.find(mood => mood.id === answers.mood)!;
  async function next() { if (step < 2) setStep(step + 1); else if (await savePreferences(answers)) setStep(3); }
  async function clear() { if (await clearPreferences()) { setAnswers({ category: "Everyone", mood: "everyday", budget: 999 }); setStep(0); } }
  return <div className="studio-layout">
    <aside className="studio-poster"><span className="studio-poster-kicker"><Sparkles size={15}/> THE PERSONAL EDIT</span><h3>YOU<br/>DO<br/><em>YOU.</em></h3><div className="studio-poster-photos"><img className="studio-photo-one" src="/images/category-women.jpg" alt="Contemporary floral styling inspiration" width={180} height={240}/><img className="studio-photo-two" src="/images/category-men.jpg" alt="Relaxed neutral styling inspiration" width={180} height={240}/><span className="studio-photo-sticker">100%<br/>YOUR ENERGY.</span></div><p>No rules. No overthinking.<br/>Just a little more you.</p><span className="studio-poster-footer">V-MART SIWAN <span>STUDIO / 02</span></span></aside>
    <div className="studio-workspace">
      {!profileReady ? <div className="studio-loading"><Sparkles size={28}/><h3>Opening your style file…</h3></div> : <>
        <div className="studio-step-top"><span>{step === 3 ? "THE EDIT IS YOURS" : `STEP 0${step + 1} OF 03`}</span><span>{step === 3 ? <><CheckCheck size={14}/> SAVED FOR YOU</> : "A LITTLE YOU GOES A LONG WAY."}</span></div>
        <div className="studio-progress" role="progressbar" aria-valuemin={0} aria-valuemax={3} aria-valuenow={Math.min(step + 1, 3)} aria-label={`Styling progress: ${Math.min(step + 1, 3)} of 3`}><motion.span animate={{ width: `${Math.min(step + 1, 3) / 3 * 100}%` }} transition={{ duration: .35 }}/></div>
        <AnimatePresence mode="wait"><motion.div key={step} className="studio-step-content" initial={{ opacity: 0, x: reduced ? 0 : 14 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: reduced ? 0 : -10 }} transition={{ duration: .22 }}>
          {step === 0 && <><span className="studio-question-overline">FIRST, THE PERSON.</span><h3>Who are we styling?</h3><p>For yourself. For your people. It all starts here.</p><div className="studio-category-options" role="group" aria-label="Choose who to style">{STYLE_CATEGORIES.map(category => { const collection = CATEGORIES.find(item => item.name === category); return <motion.button key={category} whileTap={{ scale: .98 }} className={answers.category === category ? "selected" : ""} aria-pressed={answers.category === category} onClick={() => setAnswers({ ...answers, category })}>{collection ? <img src={collection.image} alt="" width={45} height={54}/> : <span className="studio-everyone-icon"><LayoutGrid size={23}/></span>}<span><strong>{category}</strong><small>{category === "Everyone" ? "A little something for all of us." : collection?.caption}</small></span><span className="option-check">{answers.category === category && <Check size={13}/>}</span></motion.button>; })}</div></>}
          {step === 1 && <><span className="studio-question-overline">NEXT, THE FEELING.</span><h3>What’s your kind of day?</h3><p>Your mood sets the direction. We’ll find the details.</p><div className="studio-mood-options" role="group" aria-label="Choose your style mood">{STYLE_MOODS.map(mood => <motion.button key={mood.id} whileTap={{ scale: .98 }} className={answers.mood === mood.id ? "selected" : ""} aria-pressed={answers.mood === mood.id} onClick={() => setAnswers({ ...answers, mood: mood.id })}><img src={mood.image} alt="" width={95} height={105}/><span><strong>{mood.label}</strong><small>{mood.description}</small></span><span className="option-check">{answers.mood === mood.id && <Check size={13}/>}</span></motion.button>)}</div></>}
          {step === 2 && <><span className="studio-question-overline">FINALLY, YOUR COMFORT ZONE.</span><h3>Great style. Your price.</h3><p>Choose a maximum price per piece. No stretched budgets.</p><div className="studio-budget-options" role="group" aria-label="Maximum price per piece">{STYLE_BUDGETS.map(budget => <motion.button key={budget} whileTap={{ scale: .97 }} className={answers.budget === budget ? "selected" : ""} aria-pressed={answers.budget === budget} onClick={() => setAnswers({ ...answers, budget })}><span>UP TO</span><strong>{money(budget)}</strong><span className="option-check">{answers.budget === budget && <Check size={13}/>}</span></motion.button>)}</div><div className="studio-summary-chips"><span>{answers.category}</span><span>{activeMood.label}</span><span>≤ {money(answers.budget)} / piece</span></div><p className="studio-privacy"><ShieldCheck size={15}/>Saved to your private shopping session. Delete it whenever you like.</p></>}
          {step === 3 && <><span className="studio-question-overline">BASED ON YOUR CHOICES. MADE FOR YOUR DAY.</span><h3>{matching.length ? "Consider your edit, curated." : "Let’s widen the possibilities."}</h3><p>{matching.length ? `${matching.length} ${matching.length === 1 ? "style" : "styles"} that fit your category and budget, ordered for your mood.` : "No available styles match that category and budget right now. A different price range might do the trick."}</p><div className="studio-summary-chips"><span>{profile.preferences?.category}</span><span>{STYLE_MOODS.find(m => m.id === profile.preferences?.mood)?.label}</span><span>≤ {money(profile.preferences?.budget ?? 0)}</span></div><div className="studio-results" aria-label="Your curated style picks">{matching.map(({ product, reason }) => <div className="studio-result" key={product.id}><Link href={`/product/${product.slug}`} onClick={() => setStudioOpen(false)}><img src={product.image} alt={product.name} width={86} height={112}/></Link><div><span className="studio-result-category">{product.category}</span><Link href={`/product/${product.slug}`} onClick={() => setStudioOpen(false)}>{product.name}</Link><p>{reason}</p><strong>{money(product.price)}</strong><button className="text-link" onClick={() => { setStudioOpen(false); setTimeout(() => setQuickProduct({ product, color: product.colors[0].name }), 180); }}>Choose your fit<Plus size={13}/></button></div><motion.button whileTap={{ scale: .85 }} className={`studio-result-heart ${wishlist.includes(product.id) ? "saved" : ""}`} aria-label={`${wishlist.includes(product.id) ? "Unsave" : "Save"} ${product.name}`} aria-pressed={wishlist.includes(product.id)} disabled={pending} onClick={() => toggleWishlist(product.id)}><Heart size={17} fill={wishlist.includes(product.id) ? "currentColor" : "none"}/></motion.button></div>)}</div>{!matching.length && <Button variant="dark" onClick={() => setStep(2)}>Try a different budget<ArrowRight size={16}/></Button>}<p className="studio-result-disclaimer">Curated by catalogue rules, not AI profiling. Mood affects ranking; category, budget and availability are always respected.</p></>}
        </motion.div></AnimatePresence>
        {profileError && <div className="studio-error" role="alert"><span>{profileError}</span><button onClick={() => void loadProfile()} disabled={saving}>Retry loading</button></div>}
        <div className="studio-actions">{step === 3 ? <><button className="text-link" onClick={() => setStep(0)} disabled={saving}><SlidersHorizontal size={15}/>Refine my edit</button><button className="studio-clear" onClick={() => void clear()} disabled={saving}>Delete my preferences</button></> : <>{step > 0 ? <button className="text-link" onClick={() => setStep(step - 1)} disabled={saving}><ArrowLeft size={15}/>Back</button> : <span className="studio-curated-label"><Sparkles size={14}/>A considered edit. Not a guess.</span>}<Button onClick={() => void next()} disabled={saving}>{saving ? <><LoaderCircle size={16}/>Saving your edit…</> : step === 2 ? <>Reveal my edit<Sparkles size={16}/></> : <>Continue<ArrowRight size={16}/></>}</Button></>}</div>
      </>}
    </div>
  </div>;
}
export function StyleStudio() {
  const { studioOpen, setStudioOpen, profileReady } = useDiscovery();
  return <Dialog open={studioOpen} onOpenChange={setStudioOpen} title="Your style. Decoded." description="Three little choices. An edit that feels like you." className="style-studio-dialog">{studioOpen && <StudioExperience key={profileReady ? "ready" : "loading"}/>}</Dialog>;
}
export function StudioInvitation() {
  const { setStudioOpen, profile } = useDiscovery();
  const { t } = useShop();
  return <motion.div className="studio-invitation" whileHover={{ borderColor: "#82616b" }}><div className="studio-invitation-mark" aria-hidden="true"><Sparkles strokeWidth={1.2}/><span>THE<br/>STYLE<br/>STUDIO.</span></div><div className="studio-invitation-copy"><div className="eyebrow">{profile.preferences ? "YOUR PERSONAL EDIT IS WAITING" : "A LITTLE DIRECTION. A LOT OF YOU."}</div><h3>{t(profile.preferences ? "Your style, remembered." : "Not sure where to start? Start with you.", "आपका अंदाज़। आपका अपना कलेक्शन।")}</h3><p>{profile.preferences ? `${profile.preferences.category} · ${STYLE_MOODS.find(m => m.id === profile.preferences?.mood)?.label} · Up to ${money(profile.preferences.budget)} per piece` : "Three quick choices. A considered edit. No overthinking."}</p></div><button className="studio-invitation-button" onClick={() => setStudioOpen(true)}>{profile.preferences ? "Open my edit" : "Find my style"}<ArrowUpRight size={18}/></button><div className="studio-invitation-photos" aria-hidden="true"><img src="/images/category-men-detail.jpg" alt="" width={100} height={130}/><img src="/images/category-women-detail.jpg" alt="" width={100} height={130}/></div></motion.div>;
}
