const { chromium, expect: baseExpect } = require('@playwright/test');
const expect = baseExpect.configure({ timeout: 15000 });
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('artifacts', {recursive:true});
  const browser = await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors=[]; const checks=[];
  page.on('pageerror', e=>errors.push(e.message));
  const passed = label => { checks.push(label); console.log('PASS', label); };
  await page.goto('http://localhost:3000', {waitUntil:'domcontentloaded'});
  await page.waitForTimeout(900);
  await page.getByRole('button',{name:'Search products',exact:true}).click();
  await page.getByRole('textbox',{name:'Search catalogue'}).fill('kurta');
  await expect(page.locator('.search-results>a')).toHaveCount(1);
  await expect(page.locator('.search-results')).toContainText('Floral Everyday Kurta');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Search products',exact:true})).toBeFocused();
  passed('Search, Escape close, and keyboard focus restoration');
  await page.locator('.desktop-nav').getByRole('link',{name:'Women',exact:true}).click();
  await expect(page.locator('.product-grid').first().locator('.product-card')).toHaveCount(2);
  await expect(page.locator('.category-tabs').getByRole('button',{name:'Women',exact:true})).toHaveAttribute('aria-pressed','true');
  passed('Category navigation and live catalogue filtering');
  await page.locator('.budget-card-0').click();
  await expect(page.locator('.expanded-filters select').first()).toHaveValue('499');
  await expect(page.locator('.product-grid').first().locator('.product-card')).toHaveCount(2);
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await expect(page.locator('.product-grid').first().locator('.product-card')).toHaveCount(4);
  passed('Budget logic and resetting filters');
  const favourite = page.getByRole('button',{name:'Save Relaxed Linen Shirt to wishlist',exact:true});
  await favourite.click();
  await expect(page.getByRole('button',{name:'Remove Relaxed Linen Shirt from wishlist',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.reload({waitUntil:'domcontentloaded'});
  await expect(page.getByRole('button',{name:'Remove Relaxed Linen Shirt from wishlist',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Wishlist, 1 saved items',exact:true}).click();
  await expect(page.locator('.wishlist-line')).toHaveCount(1);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  passed('Wishlist persists across reloads');
  const firstCard=page.locator('.product-card').first();
  await firstCard.scrollIntoViewIfNeeded();
  await firstCard.hover();
  await firstCard.getByRole('button',{name:'Quick add',exact:true}).click();
  const quick = page.getByRole('dialog');
  await quick.getByRole('button',{name:'M',exact:true}).click();
  await quick.getByRole('button',{name:'Add to bag',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your bag (1)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Increase Relaxed Linen Shirt quantity',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your bag (2)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Decrease Relaxed Linen Shirt quantity',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your bag (1)',exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload({waitUntil:'domcontentloaded'});
  await expect(page.getByRole('button',{name:'Open shopping bag, 1 items',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open shopping bag, 1 items',exact:true}).click();
  await expect(page.locator('.cart-line')).toHaveCount(1);
  await page.screenshot({path:'artifacts/desktop-cart.png'});
  passed('Variant-aware quick add, quantity controls, and persistent cart');
  await page.getByRole('link',{name:'Continue to checkout',exact:true}).click();
  await expect(page).toHaveURL(/\/checkout$/);
  await page.getByLabel('Full name',{exact:true}).fill('Demo Shopper');
  await page.getByLabel('Email address',{exact:true}).fill('demo.shopper@example.test');
  await page.getByLabel('Mobile number',{exact:true}).fill('9876543210');
  await page.getByLabel('Your delivery address',{exact:true}).fill('12 Example Lane, Demo Locality');
  await page.getByLabel('Town / city',{exact:true}).fill('Siwan');
  await page.getByLabel('PIN code',{exact:true}).fill('841226');
  await page.screenshot({path:'artifacts/checkout-details.png'});
  await page.getByRole('button',{name:'Continue to delivery',exact:true}).click();
  await expect(page.getByRole('heading',{name:'YOUR STYLE. YOUR WAY.',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Check',exact:true}).click();
  await expect(page.locator('.pin-result')).toContainText('Hello, Siwan');
  await page.getByRole('button',{name:'Continue to payment',exact:true}).click();
  await page.locator('.payment-tabs').getByRole('button',{name:'Card',exact:true}).click();
  await expect(page.locator('.demo-bank-card')).toContainText('4242');
  await page.locator('.payment-tabs').getByRole('button',{name:'Netbanking',exact:true}).click();
  await page.getByLabel('Demo bank',{exact:true}).selectOption('HDFC Bank');
  await page.locator('.payment-tabs').getByRole('button',{name:'UPI',exact:true}).click();
  await expect(page.locator('.payment-preview')).toContainText('No real UPI ID');
  await page.getByLabel('I understand this is a prototype.',{exact:false}).check();
  await page.getByLabel('Test a declined payment instead',{exact:true}).check();
  await page.getByRole('button',{name:/Place demo order/}).click();
  await expect(page.locator('.checkout-form').getByRole('alert')).toContainText('Simulated payment declined');
  await page.screenshot({path:'artifacts/checkout-payment.png'});
  passed('Guest details, delivery PIN check, three payment methods, and failure recovery');
  await page.getByRole('button',{name:/Place demo order/}).click();
  await expect(page.getByRole('heading',{level:1})).toContainText('LOOKING GOOD,', {timeout:15000});
  await expect(page).toHaveURL(/order=VM-/);
  const orderId=new URL(page.url()).searchParams.get('order');
  await page.reload({waitUntil:'domcontentloaded'});
  await expect(page.getByRole('heading',{level:1})).toContainText('LOOKING GOOD,');
  await expect(page.locator('.success-order-card')).toContainText(orderId);
  await expect(page.getByRole('button',{name:'Open shopping bag, 0 items',exact:true})).toBeVisible();
  await page.waitForTimeout(600);
  await page.screenshot({path:'artifacts/order-success.png'});
  passed('Saved order receipt reloads and purchased cart clears');
  const stranger=await browser.newContext();
  const forbidden=await stranger.request.get(`http://localhost:3000/api/orders/${orderId}`);
  expect(forbidden.status()).toBe(404);
  const overstock=await context.request.post('http://localhost:3000/api/shop',{data:{action:'add',productId:'linen-shirt',size:'M',color:'Sand',quantity:100}});
  expect(overstock.status()).toBe(400);
  const invalidPin=await context.request.get('http://localhost:3000/api/delivery?pin=000000');
  expect(invalidPin.status()).toBe(400);
  const newsletter=await context.request.post('http://localhost:3000/api/newsletter',{data:{email:'demo.style@example.test'}});
  expect(newsletter.status()).toBe(200);
  passed('Session-private orders, server stock validation, invalid PIN rejection, and newsletter persistence');
  await page.goto('http://localhost:3000/product/relaxed-linen-shirt', {waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'Size guide',exact:true}).click();
  await expect(page.getByRole('table')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:/Zoom image 1/}).click();
  await expect(page.locator('.zoom-image-viewport')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'View detail image',exact:true}).click();
  await expect(page.getByRole('button',{name:'View detail image',exact:true})).toHaveAttribute('aria-pressed','true');
  passed('Product gallery, image zoom, and size guide');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const phone=await mobile.newPage();
  phone.on('pageerror',e=>errors.push(e.message));
  await phone.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
  await phone.getByRole('button',{name:'Open navigation menu',exact:true}).click();
  await phone.getByRole('dialog').getByRole('link',{name:'02 Women',exact:false}).count().catch(()=>{});
  await phone.locator('.mobile-menu-links').getByRole('link').filter({hasText:'Kids'}).click();
  await expect(phone.locator('.product-grid').first().locator('.product-card')).toHaveCount(1);
  expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await phone.getByRole('button',{name:'हिंदी',exact:true}).click();
  await expect(phone.locator('html')).toHaveAttribute('lang','hi');
  await expect(phone.getByRole('heading',{level:1})).toContainText('सीवान');
  passed('Mobile navigation, responsive layout, and Hindi language toggle');
  expect(errors).toEqual([]);
  fs.writeFileSync('artifacts/commerce-results.json',JSON.stringify({checks,orderId,errors},null,2));
  console.log(`ALL ${checks.length} COMMERCE CHECK GROUPS PASSED`);
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
