const { chromium, expect: baseExpect } = require('@playwright/test');
const expect = baseExpect.configure({ timeout: 15000 });
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('artifacts/edition-02', { recursive: true });
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage(); const errors = []; const checks = [];
  page.on('pageerror', error => errors.push(error.message));
  const pass = label => { checks.push(label); console.log('PASS', label); };
  await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => document.fonts.ready); await page.waitForTimeout(1000);
  await page.screenshot({ path: 'artifacts/edition-02/desktop-hero.png' });
  await page.locator('.edition-campaign-tabs').getByRole('button', { name: /celebration/i }).click();
  await expect(page.locator('.hero')).toHaveClass(/hero-mood-celebration/);
  await expect(page.getByRole('button', { name: 'Shop The celebration edit', exact: true })).toBeVisible();
  await page.waitForTimeout(700); await page.screenshot({ path: 'artifacts/edition-02/celebration-hero.png' });
  await page.locator('.edition-campaign-tabs').getByRole('button', { name: /everyday/i }).click();
  pass('Visitor-controlled campaign switching');
  await page.getByRole('button', { name: 'STYLE IN 3D', exact: true }).click();
  await expect(page.locator('.expanded-scene canvas')).toBeVisible();
  await page.getByRole('button', { name: 'Liquid silver', exact: true }).click();
  await expect(page.locator('.atelier-stage')).toHaveClass(/atelier-silver/);
  await page.waitForTimeout(400);
  const before = await page.locator('.expanded-scene canvas').screenshot();
  await page.getByRole('button', { name: 'Rotate bag right', exact: true }).click();
  await page.waitForTimeout(500);
  const after = await page.locator('.expanded-scene canvas').screenshot();
  expect(before.equals(after)).toBe(false);
  await page.getByRole('button', { name: 'After dark', exact: true }).click();
  await expect(page.getByRole('button', { name: 'After dark', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Reset bag view', exact: true }).click();
  await page.waitForTimeout(400); await page.screenshot({ path: 'artifacts/edition-02/3d-atelier.png' });
  await page.getByRole('button', { name: 'Signature scarlet', exact: true }).click();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'STYLE IN 3D', exact: true })).toBeFocused();
  pass('Live 3D finishes, keyboard rotation, reset, lighting and focus restoration');
  await page.keyboard.press('Control+k'); await expect(page.getByRole('textbox', { name: 'Search catalogue' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search catalogue' }).fill('linen');
  await expect(page.locator('.search-results>a')).toHaveCount(1);
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  pass('Keyboard command search');
  await page.locator('.nav-studio-button').click();
  await expect(page.getByRole('heading', { name: 'Who are we styling?', exact: true })).toBeVisible();
  await page.locator('.studio-category-options').getByRole('button', { name: /Women/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Continue', exact: true }).click();
  await page.locator('.studio-mood-options').getByRole('button', { name: /Off-duty energy/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Continue', exact: true }).click();
  await page.locator('.studio-budget-options').getByRole('button', { name: /₹999/ }).click();
  await page.getByRole('button', { name: 'Reveal my edit', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Consider your edit, curated.', exact: true })).toBeVisible();
  await expect(page.locator('.studio-result')).toHaveCount(2);
  await expect(page.locator('.studio-result').first()).toContainText('The Wide-Leg Denim');
  const profile = await (await context.request.get('http://localhost:3000/api/style')).json();
  expect(profile.preferences).toEqual({ category: 'Women', mood: 'weekend', budget: 999 });
  await page.screenshot({ path: 'artifacts/edition-02/style-results.png' });
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload({ waitUntil: 'domcontentloaded' }); await page.locator('.nav-studio-button').click();
  await expect(page.getByRole('heading', { name: 'Consider your edit, curated.', exact: true })).toBeVisible();
  const stranger = await browser.newContext();
  const strangerProfile = await (await stranger.request.get('http://localhost:3000/api/style')).json();
  expect(strangerProfile.preferences).toBe(null);
  const invalidProfile = await context.request.post('http://localhost:3000/api/style', { data: { category: 'Women', mood: 'weekend', budget: 123 } });
  expect(invalidProfile.status()).toBe(400);
  pass('Saved preferences, strict budget matches, mood ranking, reload persistence and session isolation');
  await page.getByRole('button', { name: 'Delete my preferences', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Who are we styling?', exact: true })).toBeVisible();
  expect((await (await context.request.get('http://localhost:3000/api/style')).json()).preferences).toBe(null);
  await page.screenshot({ path: 'artifacts/edition-02/style-studio.png' });
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  pass('Style profile deletion');
  await page.locator('.lookbook-tabs').getByRole('button', { name: /Weekend uniform/ }).click();
  await page.getByRole('button', { name: 'Build this look', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'One look. Your way.', exact: true })).toBeVisible();
  const tee = page.locator('.look-builder-piece').filter({ hasText: 'Essential Textured Tee' });
  const shoes = page.locator('.look-builder-piece').filter({ hasText: 'Everyday Court Sneakers' });
  await tee.getByRole('button', { name: 'M', exact: true }).click();
  await shoes.getByRole('button', { name: '8', exact: true }).click();
  await shoes.getByRole('checkbox').uncheck(); await expect(page.locator('.look-builder-total')).toContainText('₹399');
  await shoes.getByRole('checkbox').check(); await expect(page.locator('.look-builder-total')).toContainText('₹1,698');
  await page.screenshot({ path: 'artifacts/edition-02/build-the-look.png' });
  await page.getByRole('button', { name: 'Add the look to bag', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your bag (2)', exact: true })).toBeVisible();
  await expect(page.locator('.cart-line')).toHaveCount(2);
  const stateBefore = await (await context.request.get('http://localhost:3000/api/shop')).json();
  const invalidBundle = await context.request.post('http://localhost:3000/api/shop', { data: { action: 'addMany', items: [{ productId: 'linen-shirt', size: 'M', color: 'Sand', quantity: 1 }, { productId: 'court-sneakers', size: 'NONEXISTENT', color: 'Cream', quantity: 1 }] } });
  expect(invalidBundle.status()).toBe(400);
  const stateAfter = await (await context.request.get('http://localhost:3000/api/shop')).json();
  expect(stateAfter.cart).toEqual(stateBefore.cart);
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  pass('Outfit variant selection, exact totals and atomic whole-look cart operation');
  await page.goto('http://localhost:3000/product/relaxed-linen-shirt', { waitUntil: 'domcontentloaded' });
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('vmart-recently-viewed') || '[]'))).toContain('linen-shirt');
  await page.goto('http://localhost:3000/product/floral-everyday-kurta', { waitUntil: 'domcontentloaded' });
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('vmart-recently-viewed') || '[]'))).toContain('floral-kurta');
  await expect(page.locator('.recent-product')).toHaveCount(1);
  await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('.recent-product')).toHaveCount(2);
  await page.getByRole('button', { name: 'Clear history', exact: true }).click(); await expect(page.locator('.recent-product')).toHaveCount(0);
  pass('Device-local browsing history persists and clears');
  await page.goto('http://localhost:3000/?category=Men&budget=799&size=M&sort=high&view=all#arrivals', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('#arrivals .product-card')).toHaveCount(2);
  await expect(page.locator('#arrivals .product-card').first()).toContainText('Relaxed Linen Shirt');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await expect(page.locator('.expanded-filters select').nth(1)).toHaveValue('M');
  await expect(page.locator('.expanded-filters select').nth(2)).toHaveValue('high');
  await page.getByRole('button', { name: 'Remove price filter', exact: true }).click();
  await expect(page).not.toHaveURL(/budget=/);
  pass('Shareable category, price, size and sort filters survive reload');
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const phone = await mobile.newPage(); phone.on('pageerror', error => errors.push(error.message));
  await phone.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' }); await phone.evaluate(() => document.fonts.ready); await phone.waitForTimeout(900);
  expect(await phone.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await expect(phone.getByRole('navigation', { name: 'Mobile shopping shortcuts', exact: true })).toBeVisible();
  await phone.screenshot({ path: 'artifacts/edition-02/mobile-hero.png' });
  await phone.getByRole('button', { name: 'Open Style Studio', exact: true }).click();
  await expect(phone.getByRole('heading', { name: 'Who are we styling?', exact: true })).toBeVisible();
  await expect(phone.getByRole('dialog')).toHaveCSS('opacity', '1');
  await expect(phone.locator('.studio-step-content')).toHaveCSS('opacity', '1');
  await phone.screenshot({ path: 'artifacts/edition-02/mobile-studio.png' });
  await phone.getByRole('dialog').getByRole('button', { name: 'Close dialog', exact: true }).click();
  await expect(phone.getByRole('dialog')).toHaveCount(0);
  await phone.goto('http://localhost:3000/product/relaxed-linen-shirt', { waitUntil: 'domcontentloaded' });
  await expect(phone.locator('.product-purchase-bar')).toBeVisible();
  await phone.locator('.product-purchase-bar').getByRole('button', { name: 'Choose my fit', exact: true }).click();
  await expect(phone.locator('#product-sizes')).toBeInViewport();
  await phone.screenshot({ path: 'artifacts/edition-02/mobile-product-fit.png' });
  await phone.goto('http://localhost:3000/checkout', { waitUntil: 'domcontentloaded' });
  await expect(phone.getByRole('navigation', { name: 'Mobile shopping shortcuts', exact: true })).toHaveCount(0);
  expect(await phone.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  pass('Mobile dock, Style Studio, contextual fit bar and uncluttered checkout');
  expect(errors).toEqual([]);
  fs.writeFileSync('artifacts/edition-02/upgrade-results.json', JSON.stringify({ checks, errors }, null, 2));
  console.log(`ALL ${checks.length} UPGRADE CHECK GROUPS PASSED`);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
